//KN02_LoadValues
//FG v202103 2024/02/09 18:04:40
//Z_KeyNValue レコードの値をプロセス変数にロード


vKN02_varKN_ID:=[Z_KeyNValue]KN_ID
vKN02_varKN_KEY:=[Z_KeyNValue]KN_KEY
vKN02_varKN_CODE:=[Z_KeyNValue]KN_CODE
vKN02_varKN_VALUE:=[Z_KeyNValue]KN_VALUE
vKN02_varKN_LONG_VALUE:=[Z_KeyNValue]KN_LONG_VALUE
vKN02_varKN_SORT_ORDER:=[Z_KeyNValue]KN_SORT_ORDER
vKN02_varKN_DEL_FLAG:=[Z_KeyNValue]KN_DEL_FLAG
