//PR02_SaveValues
//FG v202103 2024/02/07 20:50:34
//PASSWORD_RESETS プロセス変数の値をレコードに保存


[PASSWORD_RESETS]PR_ID:=vPR02_varPR_ID
[PASSWORD_RESETS]PR_US_ID:=vPR02_varPR_US_ID
[PASSWORD_RESETS]PR_EMAIL:=vPR02_varPR_EMAIL
[PASSWORD_RESETS]PR_TOKEN:=vPR02_varPR_TOKEN
[PASSWORD_RESETS]PR_CREATE_AT:=vPR02_varPR_CREATE_AT
[PASSWORD_RESETS]PR_DEL_FLAG:=vPR02_varPR_DEL_FLAG
