//PR_DelAll
//method_generator 2024/02/07 15:04:10
//PASSWORD_RESETS レコード削除

READ WRITE([PASSWORD_RESETS])
ALL RECORDS([PASSWORD_RESETS])
DELETE SELECTION([PASSWORD_RESETS])
READ ONLY([PASSWORD_RESETS])

