//US02_LoadValues
//FG v202103 2024/02/11 21:23:57
//USERS レコードの値をプロセス変数にロード


vUS02_varUS_ID:=[USERS]US_ID
vUS02_varUS_NAME:=[USERS]US_NAME
vUS02_varUS_EMAIL:=[USERS]US_EMAIL
vUS02_varUS_EMAIL_VERIFIED_AT:=[USERS]US_EMAIL_VERIFIED_AT
vUS02_varUS_PASSWORD:=[USERS]US_PASSWORD
vUS02_varUS_REMEMBER_TOKEN:=[USERS]US_REMEMBER_TOKEN
vUS02_varUS_CREATE_AT:=[USERS]US_CREATE_AT
vUS02_varUS_UPDATE_AT:=[USERS]US_UPDATE_AT
vUS02_varUS_DEL_FLAG:=[USERS]US_DEL_FLAG
